### ISSUE TITLE
sealing violation: can't seal package com.klst.einvoice

### ISSUE THREAD

**Issue by homebeaver** [klst-de/AD-e-invoice#1]
21:52:05.072   ArchiveEngine.tranformToXML: >>>>>>>>>>>> MInvoice[1051631-27012,GrandTotal=119.92] DocStatus=CO [203]
21:52:05.088   MIssue.create: PDF [203]
21:52:05.103   GridField.loadLookup: (SystemStatus) [203]
===========> ExportFormatPDF.createPDF: PDF [203]
java.lang.SecurityException: sealing violation: can't seal package com.klst.einvoice: already loaded
	at java.net.URLClassLoader.getAndVerifyPackage(URLClassLoader.java:407)
	at java.net.URLClassLoader.definePackageInternal(URLClassLoader.java:420)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:452)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.compiere.print.ArchiveEngine.tranformToXML(ArchiveEngine.java:220)
	at org.compiere.print.ArchiveEngine.archive(ArchiveEngine.java:107)
	at org.spin.util.ExportFormatPDF.createPDF(ExportFormatPDF.java:101)
	at org.compiere.print.ReportEngine.createPDF(ReportEngine.java:673)
	at org.compiere.print.ReportEngine.getPDF(ReportEngine.java:648)
	at org.compiere.print.ReportEngine.getPDF(ReportEngine.java:628)
	at org.compiere.print.ReportCtl.startDocumentPrint(ReportCtl.java:378)
	at org.compiere.print.ReportCtl.start(ReportCtl.java:144)
	at org.compiere.print.ReportCtl.start(ReportCtl.java:105)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:415)

**Comment by homebeaver** [comment]
Ursache : gleicher package name in jar und AD-e-invoice

**Comment by homebeaver** [comment]
OK.
